<?php
 require_once("../libs/autoload.lib.php");
 require_once("../libs/config.inc.php");

  $h = HTTP::getInstance();
  $h->parseUrl();
  $h->sanitizeArray($_POST);
  $h->sanitizeArray($_GET);

 $m = mysqlCM::getInstance();
 if ($m->connect()) {
   HTTP::getInstance()->errMysql();
 }
 $lm = loginCM::getInstance();
 $lm->startSession();

 $index = new Template("./tpl/index.tpl");
 $head = new Template("./tpl/head.tpl");
 $menu = new Template("./tpl/menu.tpl");
 $foot = new Template("./tpl/foot.tpl");
 $foot->set("start_time", $start_time);
 $index->set("head", $head);
 $index->set("foot", $foot);
 $index->set("menu", $menu);

 if (!isset($lm->o_login) || !$lm->o_login) {
   $content = new Template("./tpl/denied.tpl");
   goto screen;
 }

 if (!isset($_GET['id']) || empty($_GET['id'])) {
   $content = new Template("./tpl/error.tpl");
   $error = "No id of list specified for patch level destination.";
   $content->set("error", $error);
   goto screen;
 }

 if (!isset($_GET['is']) || empty($_GET['is'])) {
   $content = new Template("./tpl/error.tpl");
   $error = "No id of list specified for patch level source.";
   $content->set("error", $error);
   goto screen;
 }

 $pd = new PLevel();
 $pd->id = $_GET['id'];
 if ($pd->fetchFromId()) {
   $content = new Template("./tpl/error.tpl");
   $error = "Patch level destination not found in database";
   $content->set("error", $error);
   goto screen;
 }
 $pd->fetchServer();

 if ($pd->o_server->id_owner != $lm->o_login->id) {
   $content = new Template("./tpl/error.tpl");
   $error = "You have no rights to view this patch level source!";
   $content->set("error", $error);
   goto screen;
 }
 $pd->fetchFromId();
 $pd->fetchPatches(0);

 $ps = new PLevel();
 $ps->id = $_GET['is'];
 if ($ps->fetchFromId()) {
   $content = new Template("./tpl/error.tpl");
   $error = "Patch level source not found in database";
   $content->set("error", $error);
   goto screen;
 }
 $ps->fetchServer();

 if ($ps->o_server->id_owner != $lm->o_login->id) {
   $content = new Template("./tpl/error.tpl");
   $error = "You have no rights to view this patch level source!";
   $content->set("error", $error);
   goto screen;
 }
 $ps->fetchFromId();
 $ps->fetchPatches(0);

 header("Content-type: text/plain");
 header("Content-Disposition: filename=plevel_".$ps->o_server->name."-to-".$pd->o_server->name."-patchdiag.xref");
 $pd_head = "## PATCHDIAG TOOL CROSS-REFERENCE FILE AS OF ".date('M/d/y',time())." ##\n";
 $pd_head .= "##\n";
 $pd_head .= "## Generated by WeSunSolve! (http://wesunsolve.net)\n";
 $pd_head .= "## for server named: ".$ps->o_server->name."\n";
 $pd_head .= "## and patch level: ".$ps->name."\n";
 $pd_head .= "## destination server: ".$pd->o_server->name."\n";
 $pd_head .= "## and patch level: ".$pd->name."\n";
 $pd_head .= "##\n";
 $pd_head .= "## Please note that certain patches which are listed in\n";
 $pd_head .= "## Sun's Quick Reference Section or other patch reference\n";
 $pd_head .= "## files are not publicly available, but instead are\n";
 $pd_head .= "## available only to customers of Sun Microsystems who\n";
 $pd_head .= "## have purchased an appropriate support services contract.\n";
 $pd_head .= "## For more information about Sun support services contracts\n";
 $pd_head .= "## visit www.sun.com/service\n";

// https://support.oracle.com/CSP/main/article?cmd=show&type=NOT&doctype=REFERENCE&id=1019527.1
 echo $pd_head;
 $a_p = Patchdiag::genFromPatches($ps->a_patches);
 $a_p = Patchdiag::genFromPatches($pd->a_patches, &$a_p);
// Patchdiag::cleanObsolated(&$a_p);
 echo Patchdiag::genFromArray($a_p);
 die();

screen:
  $index->set("content", $content);
  echo $index->fetch();
?>
